# -*- coding: utf-8 -*-

__author__ = 'Christine Brinchmann', 'Marie Kolvik Valøy'
__email__ = 'christibr@nmbu.no', 'mvaloy@nmbu.no'


class Board:
    """
    Creates a standard board for the snakes and ladders game if not specified
    """

    def __init__(self,
                 ladders=((1, 40), (8, 10), (36, 52), (43, 62), (49, 79),
                          (65, 82), (68, 85)),
                 chutes=((24, 5), (33, 3), (42, 30), (56, 37), (64, 27),
                         (74, 12), (87, 70)),
                 goal=90):
        self.ladders = ladders
        self.chutes = chutes
        self.goal = goal

    def goal_reached(self, position):
        """ Return True if the goal is reached"""
        return True

    def position_adjustment(self, position):
        """

        Parameters
        ----------
        position:
            the position of the player

        Returns
        -------
        0:
            if player not at the start of a snake or ladder
        num_step:
            number of position the player must move forward or backward due to
            a ladder or a snake

        """
        return 0


class Player:
    def __init__(self, board=Board()):
        self.board = board

    def move(self):
        pass


class ResilientPlayer(Player):
    def __init__(self, board=Board(), extra_steps=1):
        super().__init__(board)
        self.extra_steps = extra_steps


class LazyPlayer(Player):
    def __init__(self, board=Board(), dropped_steps=1):
        super().__init__(board)
        self.dropped_steps = dropped_steps


class Simulation:
    def __init__(self,
                 player_field=[Player(), Player()],
                 board=Board(),
                 seed=2,
                 randomize_players=True):

        self.list_player = player_field
        self.board = board
        self.seed = seed
        self.randomize_players = randomize_players
        self.variable = None

    def single_game(self):
        """

        Returns
        -------
        a tuple consisting of the number of moves and the type of the winner

        """
        return 25, 'Player'

    def run_simulation(self, num_games):
        """
        Runs a given number of games

        Parameters
        ----------
        num_games:
            number of games to play

        """
        pass

    def get_results(self):
        """
        Returns all result generated by run_simulation() calls so far so far
        a list of result tuples.

        """
        if self.variable is None:
            self.variable = 0
            return (10, 'Player'), (6, 'Player')
        else:
            return (10, 'Player'), (6, 'Player'), (10, 'Player')

    def winners_per_type(self):
        """
        Returns a dictionary mapping player types to the number of wins.
        """
        ex_dict = {'Player': 4, 'LazyPlayer': 2, 'ResilientPlayer': 5}
        return ex_dict

    def durations_per_type(self):
        """
        Returns a dictionary mapping player types to lists of game durations
        for that type

        """
        ex_dict = {'Player': [11, 25, 13], 'LazyPlayer': [39],
                   'ResilientPlayer': [8, 7, 6, 11]}
        return ex_dict

    def players_per_type(self):
        """
        Returns a dictionary showing how many players of each type participate.
        """
        ex_dict = {'Player': 3, 'LazyPlayer': 1, 'ResilientPlayer': 0}
        return ex_dict
